services:
  postgres:
    image: postgres:16.3
    restart: always
    container_name: postgres-fullstack-app-db
    ports:
      - '5432:5432'
    volumes:
      - progresDB:/data/postgres
    env_file: ./.env
volumes:
  progresDB:
